/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UtilInterface extends Interface {
  getFunction(
    nameOrSignature: "joinDigits" | "sort16" | "sort32" | "uintToDigits"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "joinDigits",
    values: [BigNumberish[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sort16",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sort32",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "uintToDigits",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "joinDigits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sort16", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sort32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uintToDigits",
    data: BytesLike
  ): Result;
}

export interface Util extends BaseContract {
  connect(runner?: ContractRunner | null): Util;
  waitForDeployment(): Promise<this>;

  interface: UtilInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  joinDigits: TypedContractMethod<
    [
      numbers: BigNumberish[],
      maxNumber: BigNumberish,
      startIndex: BigNumberish
    ],
    [[bigint, bigint] & { value: bigint; length: bigint }],
    "view"
  >;

  sort16: TypedContractMethod<[arr: BigNumberish[]], [bigint[]], "view">;

  sort32: TypedContractMethod<[arr: BigNumberish[]], [bigint[]], "view">;

  uintToDigits: TypedContractMethod<[number: BigNumberish], [bigint[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "joinDigits"
  ): TypedContractMethod<
    [
      numbers: BigNumberish[],
      maxNumber: BigNumberish,
      startIndex: BigNumberish
    ],
    [[bigint, bigint] & { value: bigint; length: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "sort16"
  ): TypedContractMethod<[arr: BigNumberish[]], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "sort32"
  ): TypedContractMethod<[arr: BigNumberish[]], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "uintToDigits"
  ): TypedContractMethod<[number: BigNumberish], [bigint[]], "view">;

  filters: {};
}
